### ISSUE TITLE
Deprecated selector in `apex-ui/index.less`

### ISSUE THREAD

**Issue by bdubaut** [apex/apex-ui#14]
Upgraded Atom to 1.13 and I have this deprecation notification for Apex-UI. It also crashes quite a lot, I am trying to get some logs for the crashes.

## Deprecation message:

In `apex-ui/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor[mini].is-focused::shadow .cursor` => `atom-text-editor[mini].is-focused.editor .cursor`

* `atom-text-editor[mini] .placeholder-text,
atom-text-editor[mini]::shadow .placeholder-text` => `atom-text-editor[mini] .placeholder-text,
atom-text-editor[mini].editor .placeholder-text`

* `atom-text-editor[mini] .selection .region,
atom-text-editor[mini]::shadow .selection .region` => `atom-text-editor[mini] .selection .region,
atom-text-editor[mini].editor .selection .region`

* `atom-text-editor[mini] .cursor,
atom-text-editor[mini]::shadow .cursor` => `atom-text-editor[mini] .cursor,
atom-text-editor[mini].editor .cursor`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by tj** [comment]
Hmm weird I'm running 1.13 and mine seems fine, no warnings

**Comment by bdubaut** [comment]
here's what I am running running 
```
Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
--
MacOS Sierra 10.12.2
```
I reinstalled Atom and the deprecation warnings are still here. The app still crashes since the update 1.13.0 but it might be an electron, chrome or Node.js related bug.

**Comment by agirton** [comment]
@tj part of this was taken care of in #12 since I removed :host.

**Comment by bdubaut** [comment]
@tj about the automatic crashes after 5min of use, it is not related to the use of the package. It appears to be an electron-related bug with MacOS. at least on my machine.

**Comment by bdubaut** [comment]
@tj so I went and tried to debug these random crashes, and they appear to be caused another package.

All good 👍
