### ISSUE TITLE
No Indication of Unsaved Files

### ISSUE THREAD

**Issue by CraigDamlo** [apex/apex-ui#27]
I don't get an indication on the tabs or the list that a file has been changed and not saved.

**Comment by Shaglock** [comment]
Same issue I have
UPD:
I've found a solution. Go to apex-ui code, `styles/tabs.less`
To the css class on line 69 add `opacity` value and the icon will be shown. I edited text-color a bit, so its not blue. Here is my piece of code
```
        &.modified:not(:hover) .close-icon {
            opacity: 1;
            top: 50%;
            right: @component-padding + 4px; // 4px -> half of icon size
            margin-top: -3px;
            border-color: @text-color-highlight;
        }
```
I can make pull request later if needed

**Comment by CraigDamlo** [comment]
This code works.
