### ISSUE TITLE
Black text in black buttons 

### ISSUE THREAD

**Issue by xgrimauu** [apex/apex-ui#29]
Seems like the text on the buttons (or at least the Github: Clone one) is not readable, I assume its just a color matter.

![imagen](https://user-images.githubusercontent.com/18611686/29448844-be851500-83f8-11e7-860e-9ac239bf6781.png)

**Comment by tj** [comment]
Ah nice hahah. Sorry yeah I only really styled what I use, so I probably missed all kinds of things

**Comment by xgrimauu** [comment]
Found it, 

![image](https://user-images.githubusercontent.com/18611686/29486179-74101cde-84e0-11e7-99e8-211510d6bfc4.png)

Will do a pull request. Everything else should be ok. 

Amazing theme btw!

**Comment by tj** [comment]
thanks!
