### ISSUE TITLE
Command Palette resizing

### ISSUE THREAD

**Issue by saadq** [apex/apex-ui#8]
Firstly, thanks for publishing this theme! It's awesome.

I'm having some strange behavior with the command palette. When I first open it up and don't type anything, it takes the full width of the screen:

![screen shot 2016-12-22 at 5 41 30 am](https://cloud.githubusercontent.com/assets/5678694/21423119/4e3093ac-c809-11e6-9a02-e01f60de2486.png)

After typing a little, it changes width size:

![screen shot 2016-12-22 at 5 42 11 am](https://cloud.githubusercontent.com/assets/5678694/21423138/66f7c004-c809-11e6-9431-066300d91e3a.png)

Something weird I noticed was if I closed the `tree-view`, reopened it, and *then* opened the command palette, it started off in the right position:

![screen shot 2016-12-22 at 5 44 39 am](https://cloud.githubusercontent.com/assets/5678694/21423214/be75704c-c809-11e6-85f3-6a7a21bc6ecf.png)

Everytime you open the command palette after that, it starts off at the right size. However, what's a bit weirder is if you press <kbd>esc</kbd> a couple of times from the main editor, and then open the command palette it goes back to the full size:

![screen shot 2016-12-22 at 5 48 38 am](https://cloud.githubusercontent.com/assets/5678694/21423300/5026ceb4-c80a-11e6-846f-e95d2fcbd63b.png)

Kind of a weird issue, but I'll try to look into the styles and see if anything's causing it or if it's some other package I have installed (although I don't think so since I don't have many custom packages).

**Comment by saadq** [comment]
Ok so I understand now why manipulating the `tree-view` and using <kbd>esc</kbd> was giving the strange behavior. I think the way it works is that if you have the `tree-view` in focus before opening the command palette, it will open in the right size. If you have the editor in focus before opening the command palette, it will open in the full width size (first screenshot).

**Comment by tj** [comment]
oh nice hahaha, I always have the tree closed, it's supposed to be center :D

**Comment by saadq** [comment]
On a new install of Atom, I don't seem to be having this issue anymore. I think this might have just been a mistake on my part where some other package or my custom stylesheet might have been causing the issue. Going to close this since it doesn't seem like anyone else is facing the issue either.
